import mysql.connector
import os
from dotenv import load_dotenv

load_dotenv()

con = mysql.connector.connect(
    host=os.getenv("DB_HOST"),
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    port=int(os.getenv("DB_PORT", 3306)),
    database=os.getenv("DB_DATABASE")
)
cur = con.cursor()

backgrounds = {
    'Bug':      "/static/imgs/all poke/webp backs/BugBack.webp",
    'Dragon':   "/static/imgs/all poke/webp backs/DragonBack.webp",
    'Electric': "/static/imgs/all poke/webp backs/EletricBack.webp",
    'Fairy':    "/static/imgs/all poke/webp backs/FairyBack.webp",
    'Fighting': "/static/imgs/all poke/webp backs/FightingBack.webp",
    'Fire':     "/static/imgs/all poke/webp backs/FireBack.webp",
    'Ghost':    "/static/imgs/all poke/webp backs/GhostBack.webp",
    'Grass':    "/static/imgs/all poke/webp backs/GrassBack.webp",
    'Ground':   "/static/imgs/all poke/webp backs/GroundBack.webp",
    'Ice':      "/static/imgs/all poke/webp backs/IceBack.webp",
    'Normal':   "/static/imgs/all poke/webp backs/NormalBack.webp",
    'Psychic':  "/static/imgs/all poke/webp backs/PhysicBack.webp",
    'Poison':   "/static/imgs/all poke/webp backs/PoisonBack.webp",
    'Rock':     "/static/imgs/all poke/webp backs/RockBack.webp",
    'Water':    "/static/imgs/all poke/webp backs/WaterBack.webp",
}

pokemons = [
    (1,'Beedrill','Bug',"/static/imgs/all poke/webpBug/BeedrillCard.webp"),
    (2,'Butterfree','Bug',"/static/imgs/all poke/webpBug/ButterfreeCard.webp"),
    (3,'Caterpie','Bug',"/static/imgs/all poke/webpBug/CaterpieCard.webp"),
    (4,'Kakuna','Bug',"/static/imgs/all poke/webpBug/KakunaCard.webp"),
    (5,'Metapod','Bug',"/static/imgs/all poke/webpBug/MetapodCard.webp"),
    (6,'Paras','Bug',"/static/imgs/all poke/webpBug/ParasCard.webp"),
    (7,'Parasect','Bug',"/static/imgs/all poke/webpBug/ParasectCard.webp"),
    (8,'Pinsir','Bug',"/static/imgs/all poke/webpBug/PinsirCard.webp"),
    (9,'Scyther','Bug',"/static/imgs/all poke/webpBug/ScytherCard.webp"),
    (10,'Venomoth','Bug',"/static/imgs/all poke/webpBug/VenomothCard.webp"),
    (11,'Venonat','Bug',"/static/imgs/all poke/webpBug/VenonatCard.webp"),
    (12,'Weedle','Bug',"/static/imgs/all poke/webpBug/WeedleCard.webp"),
    (13,'Dragonair','Dragon',"/static/imgs/all poke/webpDragon/DragonairCard.webp"),
    (14,'Dragonite','Dragon',"/static/imgs/all poke/webpDragon/DragoniteCard.webp"),
    (15,'Dratini','Dragon',"/static/imgs/all poke/webpDragon/DratiniCard.webp"),
    (16,'Electabuzz','Electric',"/static/imgs/all poke/webpElectric/ElectabuzzCard.webp"),
    (17,'Electrode','Electric',"/static/imgs/all poke/webpElectric/ElectrodeCard.webp"),
    (18,'Jolteon','Electric',"/static/imgs/all poke/webpElectric/JolteonCard.webp"),
    (19,'Magnemite','Electric',"/static/imgs/all poke/webpElectric/MagnemiteCard.webp"),
    (20,'Magneton','Electric',"/static/imgs/all poke/webpElectric/MagnetonCard.webp"),
    (21,'Pikachu','Electric',"/static/imgs/all poke/webpElectric/PikachuCard.webp"),
    (22,'Raichu','Electric',"/static/imgs/all poke/webpElectric/RaichuCard.webp"),
    (23,'Voltorb','Electric',"/static/imgs/all poke/webpElectric/VoltorbCard.webp"),
    (24,'Zapdos','Electric',"/static/imgs/all poke/webpElectric/ZapdosCard.webp"),
    (25,'Clefable','Fairy',"/static/imgs/all poke/webpFairy/ClefableCard.webp"),
    (26,'Clefairy','Fairy',"/static/imgs/all poke/webpFairy/ClefairyCard.webp"),
    (27,'Hitmonchan','Fighting',"/static/imgs/all poke/webpFighting/HitmonchanCard.webp"),
    (28,'Hitmonlee','Fighting',"/static/imgs/all poke/webpFighting/HitmonleeCard.webp"),
    (29,'Machamp','Fighting',"/static/imgs/all poke/webpFighting/MachampCard.webp"),
    (30,'Machoke','Fighting',"/static/imgs/all poke/webpFighting/MachokeCard.webp"),
    (31,'Machop','Fighting',"/static/imgs/all poke/webpFighting/MachopCard.webp"),
    (32,'Mankey','Fighting',"/static/imgs/all poke/webpFighting/MankeyCard.webp"),
    (33,'Primeape','Fighting',"/static/imgs/all poke/webpFighting/PrimeapeCard.webp"),
    (34,'Arcanine','Fire',"/static/imgs/all poke/webpFire/ArcanineCard.webp"),
    (35,'Charizard','Fire',"/static/imgs/all poke/webpFire/CharizardCard.webp"),
    (36,'Charmander','Fire',"/static/imgs/all poke/webpFire/CharmanderCard.webp"),
    (37,'Charmeleon','Fire',"/static/imgs/all poke/webpFire/CharmeleonCard.webp"),
    (38,'Flareon','Fire',"/static/imgs/all poke/webpFire/FlareonCard.webp"),
    (39,'Growlithe','Fire',"/static/imgs/all poke/webpFire/GrowlitheCard.webp"),
    (40,'Magmar','Fire',"/static/imgs/all poke/webpFire/MagmarCard.webp"),
    (41,'Moltres','Fire',"/static/imgs/all poke/webpFire/MoltresCard.webp"),
    (42,'Ninetales','Fire',"/static/imgs/all poke/webpFire/NinetalesCard.webp"),
    (43,'Ponyta','Fire',"/static/imgs/all poke/webpFire/PonytaCard.webp"),
    (44,'Rapidash','Fire',"/static/imgs/all poke/webpFire/RapidashCard.webp"),
    (45,'Vulpix','Fire',"/static/imgs/all poke/webpFire/VulpixCard.webp"),
    (46,'Gastly','Ghost',"/static/imgs/all poke/webpGhost/GastlyCard.webp"),
    (47,'Gengar','Ghost',"/static/imgs/all poke/webpGhost/GengarCard.webp"),
    (48,'Haunter','Ghost',"/static/imgs/all poke/webpGhost/HaunterCard.webp"),
    (49,'Bellsprout','Grass',"/static/imgs/all poke/webpGrass/BellsproutCard.webp"),
    (50,'Bulbasaur','Grass',"/static/imgs/all poke/webpGrass/BulbasaurCard.webp"),
    (51,'Exeggcute','Grass',"/static/imgs/all poke/webpGrass/ExeggcuteCard.webp"),
    (52,'Exeggutor','Grass',"/static/imgs/all poke/webpGrass/ExeggutorCard.webp"),
    (53,'Gloom','Grass',"/static/imgs/all poke/webpGrass/GloomCard.webp"),
    (54,'Ivysaur','Grass',"/static/imgs/all poke/webpGrass/IvysaurCard.webp"),
    (55,'Oddish','Grass',"/static/imgs/all poke/webpGrass/OddishCard.webp"),
    (56,'Tangela','Grass',"/static/imgs/all poke/webpGrass/TangelaCard.webp"),
    (57,'Venusaur','Grass',"/static/imgs/all poke/webpGrass/VenusaurCard.webp"),
    (58,'Victreebel','Grass',"/static/imgs/all poke/webpGrass/VictreebelCard.webp"),
    (59,'Vileplume','Grass',"/static/imgs/all poke/webpGrass/VileplumeCard.webp"),
    (60,'Weepinbell','Grass',"/static/imgs/all poke/webpGrass/WeepinbellCard.webp"),
    (61,'Cubone','Ground',"/static/imgs/all poke/webpGround/CuboneCard.webp"),
    (62,'Diglett','Ground',"/static/imgs/all poke/webpGround/DiglettCard.webp"),
    (63,'Dugtrio','Ground',"/static/imgs/all poke/webpGround/DugtrioCard.webp"),
    (64,'Marowak','Ground',"/static/imgs/all poke/webpGround/MarowakCard.webp"),
    (65,'Rhydon','Ground',"/static/imgs/all poke/webpGround/RhydonCard.webp"),
    (66,'Rhyhorn','Ground',"/static/imgs/all poke/webpGround/RhyhornCard.webp"),
    (67,'Sandshrew','Ground',"/static/imgs/all poke/webpGround/SandshrewCard.webp"),
    (68,'Sandslash','Ground',"/static/imgs/all poke/webpGround/SandslashCard.webp"),
    (69,'Articuno','Ice',"/static/imgs/all poke/webpIce/ArticunoCard.webp"),
    (70,'Jynx','Ice',"/static/imgs/all poke/webpIce/JynxCard.webp"),
    (71,'Chansey','Normal',"/static/imgs/all poke/webpNormal/ChanseyCard.webp"),
    (72,'Ditto','Normal',"/static/imgs/all poke/webpNormal/DittoCard.webp"),
    (73,'Dodrio','Normal',"/static/imgs/all poke/webpNormal/DodrioCard.webp"),
    (74,'Doduo','Normal',"/static/imgs/all poke/webpNormal/DoduoCard.webp"),
    (75,'Eevee','Normal',"/static/imgs/all poke/webpNormal/EeveeCard.webp"),
    (76,'Farfetchd','Normal',"/static/imgs/all poke/webpNormal/FarfetchdCard.webp"),
    (77,'Fearow','Normal',"/static/imgs/all poke/webpNormal/FearowCard.webp"),
    (78,'Jigglypuff','Normal',"/static/imgs/all poke/webpNormal/JigglypuffCard.webp"),
    (79,'Kangaskhan','Normal',"/static/imgs/all poke/webpNormal/KangaskhanCard.webp"),
    (80,'Lickitung','Normal',"/static/imgs/all poke/webpNormal/LickitungCard.webp"),
    (81,'Meowth','Normal',"/static/imgs/all poke/webpNormal/MeowthCard.webp"),
    (82,'Persian','Normal',"/static/imgs/all poke/webpNormal/PersianCard.webp"),
    (83,'Pidgeot','Normal',"/static/imgs/all poke/webpNormal/PidgeotCard.webp"),
    (84,'Pidgeotto','Normal',"/static/imgs/all poke/webpNormal/PidgeottoCard.webp"),
    (85,'Pidgey','Normal',"/static/imgs/all poke/webpNormal/PidgeyCard.webp"),
    (86,'Porygon','Normal',"/static/imgs/all poke/webpNormal/PorygonCard.webp"),
    (87,'Raticate','Normal',"/static/imgs/all poke/webpNormal/RaticateCard.webp"),
    (88,'Rattata','Normal',"/static/imgs/all poke/webpNormal/RattataCard.webp"),
    (89,'Snorlax','Normal',"/static/imgs/all poke/webpNormal/SnorlaxCard.webp"),
    (90,'Spearow','Normal',"/static/imgs/all poke/webpNormal/SpearowCard.webp"),
    (91,'Tauros','Normal',"/static/imgs/all poke/webpNormal/TaurosCard.webp"),
    (92,'Wigglytuff','Normal',"/static/imgs/all poke/webpNormal/WigglytuffCard.webp"),
    (93,'Arbok','Poison',"/static/imgs/all poke/webpPoison/ArbokCard.webp"),
    (94,'Ekans','Poison',"/static/imgs/all poke/webpPoison/EkansCard.webp"),
    (95,'Golbat','Poison',"/static/imgs/all poke/webpPoison/GolbatCard.webp"),
    (96,'Grimer','Poison',"/static/imgs/all poke/webpPoison/GrimerCard.webp"),
    (97,'Koffing','Poison',"/static/imgs/all poke/webpPoison/KoffingCard.webp"),
    (98,'Muk','Poison',"/static/imgs/all poke/webpPoison/MukCard.webp"),
    (99,'Nidoking','Poison',"/static/imgs/all poke/webpPoison/NidokingCard.webp"),
    (100,'Nidoqueen','Poison',"/static/imgs/all poke/webpPoison/NidoqueenCard.webp"),
    (101,'Nidoran F','Poison',"/static/imgs/all poke/webpPoison/Nidoran(F)Card.webp"),
    (102,'Nidoran M','Poison',"/static/imgs/all poke/webpPoison/Nidoran(M)Card.webp"),
    (103,'Nidorina','Poison',"/static/imgs/all poke/webpPoison/NidorinaCard.webp"),
    (104,'Nidorino','Poison',"/static/imgs/all poke/webpPoison/NidorinoCard.webp"),
    (105,'Weezing','Poison',"/static/imgs/all poke/webpPoison/WeezingCard.webp"),
    (106,'Zubat','Poison',"/static/imgs/all poke/webpPoison/ZubatCard.webp"),
    (107,'Abra','Psychic',"/static/imgs/all poke/webpPsychic/AbraCard.webp"),
    (108,'Alakazam','Psychic',"/static/imgs/all poke/webpPsychic/AlakazamCard.webp"),
    (109,'Drowzee','Psychic',"/static/imgs/all poke/webpPsychic/DrowzeeCard.webp"),
    (110,'Hypno','Psychic',"/static/imgs/all poke/webpPsychic/HypnoCard.webp"),
    (111,'Kadabra','Psychic',"/static/imgs/all poke/webpPsychic/KadabraCard.webp"),
    (112,'Mew','Psychic',"/static/imgs/all poke/webpPsychic/MewCard.webp"),
    (113,'Mewtwo','Psychic',"/static/imgs/all poke/webpPsychic/MewtwoCard.webp"),
    (114,'Mr. Mime','Psychic',"/static/imgs/all poke/webpPsychic/Mr.MimeCard.webp"),
    (115,'Aerodactyl','Rock',"/static/imgs/all poke/webpRock/AerodactylCard.webp"),
    (116,'Geodude','Rock',"/static/imgs/all poke/webpRock/GeodudeCard.webp"),
    (117,'Golem','Rock',"/static/imgs/all poke/webpRock/GolemCard.webp"),
    (118,'Graveler','Rock',"/static/imgs/all poke/webpRock/GravelerCard.webp"),
    (119,'Kabuto','Rock',"/static/imgs/all poke/webpRock/KabutoCard.webp"),
    (120,'Kabutops','Rock',"/static/imgs/all poke/webpRock/KabutopsCard.webp"),
    (121,'Omanyte','Rock',"/static/imgs/all poke/webpRock/OmanyteCard.webp"),
    (122,'Omastar','Rock',"/static/imgs/all poke/webpRock/OmastarCard.webp"),
    (123,'Onix','Rock',"/static/imgs/all poke/webpRock/OnixCard.webp"),
    (124,'Blastoise','Water',"/static/imgs/all poke/webpWater/BlastoiseCard.webp"),
    (125,'Cloyster','Water',"/static/imgs/all poke/webpWater/CloysterCard.webp"),
    (126,'Dewgong','Water',"/static/imgs/all poke/webpWater/DewgongCard.webp"),
    (127,'Goldeen','Water',"/static/imgs/all poke/webpWater/GoldeenCard.webp"),
    (128,'Golduck','Water',"/static/imgs/all poke/webpWater/GolduckCard.webp"),
    (129,'Gyarados','Water',"/static/imgs/all poke/webpWater/GyaradosCard.webp"),
    (130,'Horsea','Water',"/static/imgs/all poke/webpWater/HorseaCard.webp"),
    (131,'Kingler','Water',"/static/imgs/all poke/webpWater/KinglerCard.webp"),
    (132,'Krabby','Water',"/static/imgs/all poke/webpWater/KrabbyCard.webp"),
    (133,'Lapras','Water',"/static/imgs/all poke/webpWater/LaprasCard.webp"),
    (134,'Magikarp','Water',"/static/imgs/all poke/webpWater/MagikarpCard.webp"),
    (135,'Poliwag','Water',"/static/imgs/all poke/webpWater/PoliwagCard.webp"),
    (136,'Poliwhirl','Water',"/static/imgs/all poke/webpWater/PoliwhirlCard.webp"),
    (137,'Poliwrath','Water',"/static/imgs/all poke/webpWater/PoliwrathCard.webp"),
    (138,'Psyduck','Water',"/static/imgs/all poke/webpWater/PsyduckCard.webp"),
    (139,'Seadra','Water',"/static/imgs/all poke/webpWater/SeadraCard.webp"),
    (140,'Seaking','Water',"/static/imgs/all poke/webpWater/SeakingCard.webp"),
    (141,'Seel','Water',"/static/imgs/all poke/webpWater/SeelCard.webp"),
    (142,'Shellder','Water',"/static/imgs/all poke/webpWater/ShellderCard.webp"),
    (143,'Slowbro','Water',"/static/imgs/all poke/webpWater/SlowbroCard.webp"),
    (144,'Slowpoke','Water',"/static/imgs/all poke/webpWater/SlowpokeCard.webp"),
    (145,'Squirtle','Water',"/static/imgs/all poke/webpWater/SquirtleCard.webp"),
    (146,'Starmie','Water',"/static/imgs/all poke/webpWater/StarmieCard.webp"),
    (147,'Staryu','Water',"/static/imgs/all poke/webpWater/StaryuCard.webp"),
    (148,'Tentacool','Water',"/static/imgs/all poke/webpWater/TentacoolCard.webp"),
    (149,'Tentacruel','Water',"/static/imgs/all poke/webpWater/TentacruelCard.webp"),
    (150,'Vaporeon','Water',"/static/imgs/all poke/webpWater/VaporeonCard.webp"),
    (151,'Wartortle','Water',"/static/imgs/all poke/webpWater/WartortleCard.webp"),
]

print("Insertando backgrounds...")
for tipo, url in backgrounds.items():
    cur.execute("INSERT INTO backgrounds (type, url) VALUES (%s, %s) ON DUPLICATE KEY UPDATE url = %s", (tipo, url, url))
con.commit()
print(f"  {len(backgrounds)} backgrounds OK!")

print("Insertando pokemons...")
for p in pokemons:
    cur.execute("INSERT INTO pokemons (id, name, type, card) VALUES (%s, %s, %s, %s) ON DUPLICATE KEY UPDATE name = %s", (p[0], p[1], p[2], p[3], p[1]))
con.commit()
print(f"  {len(pokemons)} pokemons OK!")

con.close()
print("\nListo! DB poblada correctamente.")